/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_VideoMemoryMeter
#define HEADER_VideoMemoryMeter
/*
htop - VideoMemoryMeter.h
(C) 2014 ...
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

#include "Meter.h"

extern int VideoMemoryMeter_attributes[];

extern MeterClass VideoMemoryMeter_class;

#endif
